import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';

const ARCS = {
  'ordinary-left-01': {
    label: 'INFLIGHT_ALIEN_ARC_TABLE',
    address: 0x1E00,
    description: 'Full 90-degree arc table for ordinary (non-flagship) aliens departing from swarm. Used by all ordinary aliens via ArcTableLsb=0.',
    format: 'byte pairs (signed X delta, unsigned Y delta). ArcClockwise=0: Y += delta. ArcClockwise=1: Y -= delta.',
    termination: 'After 47 ticks (TempCounter2=12 animation frames, TempCounter1=3 then 4), StageOfLife increments to READY_TO_ATTACK. Also terminates early if Y+7 < $0E (off-screen).',
    expectedBytes: 103,
  },
};

function parseAsmHexLine(line) {
  const m = line.match(/^\s*[0-9A-Fa-f]+:\s{2}([0-9A-Fa-f ]{2,})/);
  if (!m) return null;
  const hexStr = m[1].trim();
  const bytes = [];
  for (let i = 0; i < hexStr.length; i += 3) {
    const b = parseInt(hexStr.substring(i, i + 2), 16);
    if (!isNaN(b)) bytes.push(b);
  }
  return bytes;
}

function findArcData(sourcePath, arcName, expectedSize) {
  const arc = ARCS[arcName];
  if (!arc) {
    console.error(`ERROR: unknown arc "${arcName}". Available: ${Object.keys(ARCS).join(', ')}`);
    process.exit(1);
  }

  const content = readFileSync(sourcePath, 'utf-8');
  const lines = content.split('\n');

  let inTable = false;
  let accumulated = [];
  let foundLabel = false;
  let expectedAddr = arc.address;

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];

    if (!inTable) {
      if (line.trim().startsWith(arc.label + ':')) {
        inTable = true;
        foundLabel = true;
      }
      continue;
    }

    if (line.trim() === '' || (line.trim().startsWith(';') && !line.trim().startsWith('; '))) {
      continue;
    }

    const bytes = parseAsmHexLine(line);
    if (bytes) {
      accumulated.push(...bytes);
      const addrMatch = line.match(/^\s*([0-9A-Fa-f]+):/);
      if (addrMatch) {
        expectedAddr = parseInt(addrMatch[1], 16) + bytes.length;
      }
    } else {
      break;
    }

    if (accumulated.length >= expectedSize) {
      break;
    }
  }

  if (!foundLabel) {
    console.error(`ERROR: label "${arc.label}" not found in source file.`);
    process.exit(1);
  }

  if (accumulated.length !== arc.expectedBytes) {
    console.error(`ERROR: expected ${arc.expectedBytes} bytes for "${arc.label}" but found ${accumulated.length}.`);
    console.error('Raw extracted:', accumulated.map(b => b.toString(16).padStart(2, '0')).join(' '));
    process.exit(1);
  }

  return accumulated;
}

function buildPairs(bytes) {
  const pairs = [];
  for (let i = 0; i + 1 < bytes.length; i += 2) {
    const xSigned = bytes[i] >= 0x80 ? bytes[i] - 256 : bytes[i];
    pairs.push({ xDelta: xSigned, yDelta: bytes[i + 1] });
  }
  if (bytes.length % 2 !== 0) {
    const last = bytes[bytes.length - 1];
    const xSigned = last >= 0x80 ? last - 256 : last;
    pairs.push({ xDelta: xSigned, yDelta: null, incomplete: true });
  }
  return pairs;
}

function generateSourceFile(sourcePath, outputPath, arcName, pairs) {
  const content = readFileSync(sourcePath, 'utf-8');
  const sha = createHash('sha256').update(content).digest('hex').toUpperCase();
  const now = new Date().toISOString().split('T')[0];
  const arc = ARCS[arcName];

  const js = `// Generated by tools/extract_arc_tables.mjs
// Do not edit manually — regenerate with:
//   node tools/extract_arc_tables.mjs --source <asm-path> --arc ${arcName}

// Source: local ASM disassembly (NOT included in distribution)
// Source label: ${arc.label}
// Source address: $${arc.address.toString(16).toUpperCase()}
// Source SHA-256: ${sha}
// Generated: ${now}

// Interpretation status: PROVISIONAL — verified against INFLIGHT_ALIEN_FLIES_IN_ARC ($0D71)
// ${arc.description}
// Format: ${arc.format}
// ${arc.termination}
// Total byte pairs: ${pairs.length}

export const ORDINARY_ALIEN_ARC_01 = {
  sourceAddress: ${arc.address},
  sourceLabel: '${arc.label}',
  direction: 'clockwise',
  format: 'pairs',
  values: [
${pairs.map((p, i) => `    { x: ${String(p.xDelta).padStart(4)}, y: ${p.yDelta !== null ? p.yDelta : 'null'} }${i < pairs.length - 1 ? ',' : ''}${p.incomplete ? ' // incomplete pair' : ''}`).join('\n')}
  ],
};
`;

  writeFileSync(outputPath, js, 'utf-8');
  return sha;
}

function main() {
  const args = {};
  for (let i = 2; i < process.argv.length; i++) {
    if (process.argv[i] === '--source' && i + 1 < process.argv.length) {
      args.source = resolve(process.argv[++i]);
    } else if (process.argv[i] === '--arc' && i + 1 < process.argv.length) {
      args.arc = process.argv[++i];
    } else if (process.argv[i] === '--output' && i + 1 < process.argv.length) {
      args.output = resolve(process.argv[++i]);
    }
  }

  if (!args.source || !args.arc) {
    console.error('Usage: node extract_arc_tables.mjs --source <asm-path> --arc <arc-name> [--output <path>]');
    console.error('Available arcs:', Object.keys(ARCS).join(', '));
    process.exit(1);
  }

  if (!args.output) {
    const engineRoot = resolve(dirname(process.argv[1]), '..');
    args.output = resolve(engineRoot, 'src', 'data', 'generated', `${args.arc}.js`);
  }

  const expectedSize = ARCS[args.arc].expectedBytes;
  const bytes = findArcData(args.source, args.arc, expectedSize);
  console.error(`Extracted ${bytes.length} bytes from ${ARCS[args.arc].label} @ $${ARCS[args.arc].address.toString(16).toUpperCase()}`);
  console.error(`SHA-256 of source: ${createHash('sha256').update(readFileSync(args.source, 'utf-8')).digest('hex').toUpperCase()}`);

  const pairs = buildPairs(bytes);
  console.error(`Built ${pairs.length} coordinate pairs`);

  const sha = generateSourceFile(args.source, args.output, args.arc, pairs);
  console.error(`Generated: ${args.output}`);
  console.error(`First 3 pairs: x=${pairs[0].xDelta} y=${pairs[0].yDelta}, x=${pairs[1].xDelta} y=${pairs[1].yDelta}, x=${pairs[2].xDelta} y=${pairs[2].yDelta}`);
  console.error(`Last 3 pairs: x=${pairs[pairs.length - 3].xDelta} y=${pairs[pairs.length - 3].yDelta}, x=${pairs[pairs.length - 2].xDelta} y=${pairs[pairs.length - 2].yDelta}, x=${pairs[pairs.length - 1].xDelta} y=${pairs[pairs.length - 1].yDelta}`);

  // Determinism check: run twice, compare output
  const bytes2 = findArcData(args.source, args.arc, expectedSize);
  const sha2 = createHash('sha256').update(JSON.stringify(bytes2)).digest('hex');
  const sha1 = createHash('sha256').update(JSON.stringify(bytes)).digest('hex');
  if (sha1 === sha2) {
    console.error(`Determinism check: PASS (SHA-256 match)`);
  } else {
    console.error(`Determinism check: FAIL — extraction not deterministic!`);
    process.exit(1);
  }
}

main();
